config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get "events/new"
  post "/events/:event_id/manage_staffs" => "manager_profiles#save_staffs",
       as: :save_staffs
  get "/events/:event_id/manage_staffs" => "manager_profiles#manage_staffs",
      as: :manage_staffs
  get "/events/:event_id/remove_staff/:event_staff_id" =>
    "manager_profiles#remove_staff", as: :remove_staff
  get "/featured_events" => "welcome#featured"
  get "/popular_events" => "welcome#popular"
  get "/upcoming_events" => "welcome#index"
  get "/my_events" => "users#show"
  get "events/loading"
  get "/lookup_staffs" => "users#lookup_staff_emails"
  get "/user_info/:user_id" => "users#fetch_user_info"
  post "/paypal_hook" => "bookings#paypal_hook", as: :hook
  post "/paypal_dummy" => "bookings#paypal_dummy", as: :paypal_dummy
  get "unattend", to: "attendees#destroy", as: "unattend"
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  get "/tickets" => "bookings#index"
  get "/print/:booking_id(/:ticket_type_id)" => "printer#print", as: :print
  get "/download/:booking_id" => "printer#download", as: :download
  get "signout", to: "sessions#destroy", as: "signout"
  get "/session" => "sessions#create"
  post "/api_login" => "sessions#api_login"
  resources :manager_profiles, only: [:new, :create]
  resources :attendees
  resources :events do
    resources :bookings, only: [:create]
  end
  resources :users, only: [:show]
  get "*unmatched_route", to: "application#no_route_found"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  before_create :add_uniq_id
  before_save :calculate_amount

  belongs_to :user
  belongs_to :event
  has_many :user_tickets, dependent: :destroy
  accepts_nested_attributes_for :user_tickets
  enum payment_status: [:unpaid, :free, :paid]

  def paypal_url(return_path)
    values = {
      business: ENV["PAYPAL_BUSINESS"],
      cmd: "_xclick",
      return: "#{ENV['app_host']}#{return_path}",
      invoice: uniq_id,
      amount: amount,
      item_name: "Ticket for #{event.title}",
      item_number: id,
      notify_url: "#{ENV['paypal_notify_url']}/paypal_hook"
    }
    "#{ENV['paypal_host']}/cgi-bin/webscr?" + values.to_query
  end

  def self.validate_url
    "#{ENV['paypal_host']}/cgi-bin/webscr?cmd=_notify-validate"
  end

  private

  def calculate_amount
    cost = 0
    user_tickets.includes(:ticket_type).each do |ticket|
      cost += ticket.ticket_type.price.to_f
    end
    self.amount = cost
  end

  def add_uniq_id
    self.uniq_id = SecureRandom.hex
  end

  def check_presence_of_tickets
    presence = user_tickets.blank?
    errors.add(:user_tickets, "You cannot save without an ID") if presence
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user,
                except: [:paypal_hook, :view_booking, :paypal_dummy]
  before_action except: [:view_booking, :paypal_hook, :index, :paypal_dummy] do
    set_event
    ticket_params
    ticket_quantity_specified?
  end

  protect_from_forgery except: [:paypal_hook]

  def index
    @bookings = current_user.bookings.order(id: :desc).decorate
  end

  def create
    @booking = Booking.create(event: @event, user: current_user)
    tickets = []
    ticket_params.each do |ticket_type_id, quantity|
      quantity.to_i.times do
        user = UserTicket.new(ticket_type_id: ticket_type_id, booking: @booking)
        tickets << user
      end
    end
    UserTicket.import tickets
    @booking.save
    Booking.update_counters(@booking.id, user_tickets_count: tickets.size)
    process_free_ticket_or_redirect_paid_ticket
  end

  def paypal_hook
    params.permit!
    status = params[:payment_status]
    if status == "Completed"
      response = validate_ipn_notification(request.raw_post)
      examine_booking(response)
    end
    render nothing: true
  end

  def paypal_dummy
    redirect_to tickets_path
  end

  private

  def ticket_params
    params.require(:tickets_quantity)
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def process_free_ticket_or_redirect_paid_ticket
    if @booking.amount == 0
      @booking.free!
      trigger_booking_mail
      redirect_to tickets_path
    else
      redirect_to @booking.paypal_url(paypal_dummy_path)
    end
  end

  def validate_ipn_notification(raw)
    uri = URI.parse(Booking.validate_url)
    http = Net::HTTP.new(uri.host, uri.port)
    http.open_timeout = 60
    http.read_timeout = 60
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    http.use_ssl = true
    http.post(uri.request_uri, raw,
              "Content-Length" => "#{raw.size}",
              "User-Agent" => "EventX"
             ).body
  end

  def examine_booking(response)
    case response
    when "VERIFIED"
      @booking = Booking.find_by_uniq_id(params[:invoice])
      booking_accepted(@booking) if @booking
    when "INVALID"
    end
  end

  def ticket_quantity_specified?
    if ticket_params.values.map(&:to_i).inject(:+) <= 0
      flash[:notice] = "You have to specify quantity of ticket required!"
      redirect_to event_path(params[:event_id])
    end
  end

  def booking_accepted(booking)
    booking.paid!
    booking.update(txn_id: params[:txn_id])
    trigger_booking_mail
  end

  def trigger_booking_mail
    user = @booking.user
    event = @booking.event
    mail = EventMailer.attendance_confirmation(user, event)
    mail.deliver_later!(wait: 1.minute)
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
  def link_to_add_fields(name, f, model_class, association, cssclass, title)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object,
                          child_index: "new_#{association}") do |builder|
      render(model_class + "/" + association.to_s.singularize + "_fields", f:
             builder)
    end
    link_to name, "#", onclick: h("add_fields(this, '#{association}',
                                   \"#{escape_javascript(fields)}\")
    "), class: cssclass, title: title
  end
end

app/views/bookings/_tickets.html.erb
<div class="row">
  <% @bookings.each do |booking|%>
  <div class="col s12 m4 l4">
    <div class="card medium">
      <div class="card-image">
        <%= image_tag booking.event.image_url(:landing) %>
        <span class="card-title card-panel cyan lighten-1"><%=booking.event.title %></span>
      </div>
      <div class="card-content">
        <%= booking.show_ticket_types %>
      </div>
      <div class="card-action">
        <%= link_to content_tag(:i, "", class: "fa fa-print") + "Print", print_path(booking.id), class: "left"%>
        <%= link_to content_tag(:i, "", class: "fa fa-floppy-o") + "Download", download_path(booking.id), {class: "right", target: "_blank"}%>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/bookings/index.html.erb
<div>
  <% content_for :nav_cat do %>
        <li class="teal darken-3">
          <div class="row our-image-cover">
            <div class="col l12 m12 s12">
              <%= link_to root_path do %>
                <h3 class="header home_app_title">EventX</h3>
              <% end %>
           </div>
          </div>
        </li>
        <li class="bold"><a href="index.html" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> My Events</a>

        </li>
        <li class="bold"><a href="index.html" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Attending Events</a>
        </li>
        <li class="bold active"><%= link_to content_tag(:i, "", class: "mdi-image-palette") + "Tickets", tickets_path, class: "waves-effect waves-cyan" %>
        </li>
        <li class="bold"><a href="app-email.html" class="waves-effect waves-cyan"><i class="mdi-communication-email"></i> Account Details </a>
        </li>
        <li class="li-hover">
          <div class="row">
            <div class="col s12 m12 l12">
              <div class="sample-chart-wrapper">
                <div class="ct-chart ct-golden-section" id="ct2-chart"></div>
              </div>
            </div>
          </div>
        </li>
  <% end %>
  </div>
  <div class="our-new-custom-nav">
    <%= render partial: "layouts/nav" %>
  </div>
  <div id="main">
      <!-- START WRAPPER -->
      <div class="wrapper">

        <%= render partial: "layouts/sidebar"%>
          <%= render partial: "tickets"%>
    </div>
</div>