config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get "events/new"
  post "/events/:event_id/manage_staffs" => "manager_profiles#save_staffs",
       as: :save_staffs
  get "/events/:event_id/manage_staffs" => "manager_profiles#manage_staffs",
      as: :manage_staffs
  get "/events/:event_id/remove_staff/:event_staff_id" =>
    "manager_profiles#remove_staff", as: :remove_staff
  get "/featured_events" => "welcome#featured"
  get "/popular_events" => "welcome#popular"
  get "/upcoming_events" => "welcome#index"
  get "/my_events" => "users#show"
  get "events/loading"
  get "/lookup_staffs" => "users#lookup_staff_emails"
  get "/user_info/:user_id" => "users#fetch_user_info"
  post "/paypal_hook" => "bookings#paypal_hook", as: :hook
  post "/paypal_dummy" => "bookings#paypal_dummy", as: :paypal_dummy
  get "unattend", to: "attendees#destroy", as: "unattend"
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  get "/tickets" => "bookings#index"
  get "/print/:booking_id(/:ticket_type_id)" => "printer#print", as: :print
  get "/download/:booking_id" => "printer#download", as: :download
  get "signout", to: "sessions#destroy", as: "signout"
  get "/session" => "sessions#create"
  post "/api_login" => "sessions#api_login"
  resources :manager_profiles, only: [:new, :create]
  resources :attendees
  resources :events do
    resources :bookings, only: [:create]
  end
  resources :users, only: [:show]
  get "*unmatched_route", to: "application#no_route_found"
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :bookings
  has_many :user_tickets, through: :bookings
  has_many :events_attending, through: :bookings, source: "event"
  has_many :event_staffs
  has_one :manager_profile
  has_many :events, through: :manager_profile

  def self.from_omniauth(auth)
    return auth unless auth
    provider = auth["provider"]
    where(provider: provider, uid: auth["uid"]).first_or_create do |user|
      user.provider = provider
      user.uid = auth["uid"]
      user.profile_url = auth["info"][:image]
      user.first_name = auth["info"][:name]
      user.email = auth["info"][:email]
      user.save!
    end
  end

  def self.lookup_email(email)
    where(arel_table[:email].matches("%#{email}%")).limit(5).
      pluck(:email, :id).map do |mail, id|
      { "value": mail, "data": id }
    end
  end

  def event_manager?
    !manager_profile.nil?
  end

  def generate_auth_token
    payload = { user_id: id, email: email }
    AuthToken.encode(payload)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user
  respond_to :json, :html, :js

  def show
    manager_profile = current_user.manager_profile
    manager_profile_id = manager_profile ? manager_profile.id : nil
    @events = Event.my_event_search(search_params, manager_profile_id)
    respond_with @events
  end

  def lookup_staff_emails
    render json: User.lookup_email(params[:term])
  end

  def fetch_user_info
    @user = User.find_by(id: params[:user_id])
    render layout: false, partial: "fetch_user_info",
           locals: { user: @user, role: nil }
  end

  private

  def search_params
    params.permit(:event_name).symbolize_keys
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def sign_in_provider
    {
      facebook: { name: "Facebook", class:
        "blue darken-3", icon_class: "fa-facebook" },
      twitter:  { name: "Twitter", class:
        "blue", icon_class: "fa-twitter" },
      google_oauth2: { name: "Google", class:
        "red darken-4", icon_class: "fa-google-plus" },
      linkedin: { name: "LinkedIn", class:
        "blue darken-4", icon_class: "fa-linkedin" },
      github: { name: "Github", class:
        "grey darken-4", icon_class: "fa-github" },
      tumblr: { name: "Tumblr", class:
        "blue-grey darken-3", icon_class: "fa-tumblr" }
    }
  end
end

app/views/users/__old.html.erb
<div>

  <% content_for :nav_cat do %>
        <li class="teal darken-3">


          <div class="row our-image-cover">
            <div class="col l12 m12 s12">
              <%= link_to root_path do %>
                <h3 class="header home_app_title">EventX</h3>
              <% end %>
           </div>
          </div>
        </li>
        <li class="bold active"><a href="index.html" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> My Events</a>

        </li>
        <li class="bold"><a href="index.html" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Attending Events</a>

        </li>
        <li class="bold"><a href="app-email.html" class="waves-effect waves-cyan"><i class="mdi-image-palette "></i> Tickets </a>
        </li>
        <li class="bold"><a href="app-email.html" class="waves-effect waves-cyan"><i class="mdi-communication-email"></i> Account Details </a>
        </li>

        <!--<li class="bold"><a href="<%#= signout_path %>" class="waves-effect waves-cyan"><i class="mdi-communication-email"></i> Logout </a>-->
        </li>

        <li class="li-hover">
          <div class="row">
            <div class="col s12 m12 l12">
              <div class="sample-chart-wrapper">
                <div class="ct-chart ct-golden-section" id="ct2-chart"></div>
              </div>
            </div>
          </div>
        </li>

  <% end %>
  </div>
  <div class="our-new-custom-nav">
    <%= render partial: "layouts/nav" %>
  </div>
  <div id="main">
      <!-- START WRAPPER -->
      <div class="wrapper">

        <%= render partial: "layouts/sidebar"%>
        <%= render partial: "users/dashboard"%>
      </div>
  </div>
</div>

app/views/users/_dashboard.html.erb
<!-- START CONTENT -->
<section id="content" >

  <!--start container-->
  <div class="our-modified-container container" id ="hel">
    <div class="row center">
      <div class="col l8 m8 s12 offset-l3 offset-m2">
          <%= form_tag user_path(current_user), method: :get, id: "user_event_search_form", remote: true do %>
            <%= content_tag :div, class: "input-field col l6 m6 s8" do %>
              <%= content_tag :i, "search", class: "material-icons prefix" %>
              <%= text_field_tag(:event_name, "", placeholder: "Search By Event Name") %>
            <% end %>
            <%= content_tag :div, class: "input-field col l2 m2 s4" do %>
              <%= button_tag "Search", type: "submit", class: "btn" %>
            <% end %>
          <% end %>
      </div>
    </div>
    <label>
      <% all_events = @events %>
      <%= "Result: #{all_events.size} event".pluralize(all_events.size)%>
    </label>
    <table class="centered striped">
      <thead>
      <tr>
        <th data-field="id">Name</th>
        <th data-field="name">Location</th>
        <th data-field="price">Date</th>
        <th data-field="price">Status</th>
        <th data-field="price"></th>
      </tr>
      </thead>

      <tbody id="events_lists">
        <%= render partial: "users/eventlist"%>
      </tbody>
    </table>
    <a class="btn-floating btn-large waves-effect waves-light teal" style="position: fixed; bottom: 25px; right: 50px;" href="<%= events_new_path%>"><i class="material-icons">add</i></a>
    </div>
    <!--end container-->
</section>
<!-- END CONTENT -->

app/views/users/_eventlist.html.erb
<%  @events.each do |event| %>
<tr>
  <td><%= event.title %></td>
  <td><%= event.location %></td>
  <td><%= event.start_date.strftime("%d %B, %Y") %></td>
  <!-- <td>Opened</td> -->
  <td><a href="" class="dropdown-button btn-floating btn waves-effect waves-light transparent z-depth-0" data-activates="dropdown-<%= "#{event.id}" %>"><i class="fa fa-ellipsis-v" style="color: black;" ></i></a></td>
  <ul class="dropdown-content" id="dropdown-<%= "#{event.id}" %>">
    <li data-eventId="<%= event.id %>"><%= link_to "Edit Event", edit_event_path(event), id:"edit-event", class:"our-dropdown-content", data: {eventid: event.id } %></li>
    <li><a class="our-dropdown-content" href="">Disable Event</a></li>
    <!-- <li><a class="our-dropdown-content" href="">View Event</a></li> -->
    <li><%= link_to "View Event", event, class: "our-dropdown-content" %></li>
    <li><a class="our-dropdown-content" href="">View Ticket</a></li>
    <li><%= link_to "Manage Staffs", manage_staffs_path(event), class:"our-dropdown-content", data: {eventid: event.id } %></li>
  </ul>
</tr>
<% end %>

app/views/users/_fetch_user_info.html.erb
<div class="chip">
  <img src="<%= user.profile_url %>" alt="Contact Person">
  <%= "#{user.first_name} #{user.last_name} #{role}" %>&emsp;
  <a href="#" data-remote="true"><span class="remove_staff">x</span></a>
  <input type="hidden" name = "event[event_staffs_attributes][][user_id]" value = "<%= user.id %>" />
</div>

app/views/users/show.html.erb
<div>
  <% content_for :nav_cat do %>
        <li class="teal darken-3">
          <div class="row our-image-cover">
            <div class="col l12 m12 s12">
              <%= link_to root_path do %>
                <h3 class="header home_app_title">EventX</h3>
              <% end %>
           </div>
          </div>
        </li>
        <li class="bold active"><a href="index.html" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> My Events</a>

        </li>
        <li class="bold"><a href="index.html" class="waves-effect waves-cyan"><i class="mdi-action-dashboard"></i> Attending Events</a>

        </li>
        <li class="bold"><%= link_to content_tag(:i, "", class: "mdi-image-palette") + "Tickets", tickets_path, class: "waves-effect waves-cyan" %>
        </li>
        <li class="bold"><a href="app-email.html" class="waves-effect waves-cyan"><i class="mdi-communication-email"></i> Account Details </a>
        </li>
        <li class="li-hover">
          <div class="row">
            <div class="col s12 m12 l12">
              <div class="sample-chart-wrapper">
                <div class="ct-chart ct-golden-section" id="ct2-chart"></div>
              </div>
            </div>
          </div>
        </li>
  <% end %>
  </div>
  <div class="our-new-custom-nav">
    <%= render partial: "layouts/nav" %>
  </div>
  <div id="main">
      <!-- START WRAPPER -->
      <div class="wrapper">

        <%= render partial: "layouts/sidebar"%>
        <%= render partial: "users/dashboard"%>
    </div>
</div>

app/views/users/show.js.erb
<% unless @events.empty? %>
$('#events_lists').html("<%=j render partial: 'users/eventlist' %>")
<% else %>
$('#events_lists').html("<h4>No Event found</h4>")
<% end %>