config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get "events/new"
  post "/events/:event_id/manage_staffs" => "manager_profiles#save_staffs",
       as: :save_staffs
  get "/events/:event_id/manage_staffs" => "manager_profiles#manage_staffs",
      as: :manage_staffs
  get "/events/:event_id/remove_staff/:event_staff_id" =>
    "manager_profiles#remove_staff", as: :remove_staff
  get "/featured_events" => "welcome#featured"
  get "/popular_events" => "welcome#popular"
  get "/upcoming_events" => "welcome#index"
  get "/my_events" => "users#show"
  get "events/loading"
  get "/lookup_staffs" => "users#lookup_staff_emails"
  get "/user_info/:user_id" => "users#fetch_user_info"
  post "/paypal_hook" => "bookings#paypal_hook", as: :hook
  post "/paypal_dummy" => "bookings#paypal_dummy", as: :paypal_dummy
  get "unattend", to: "attendees#destroy", as: "unattend"
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  get "/tickets" => "bookings#index"
  get "/print/:booking_id(/:ticket_type_id)" => "printer#print", as: :print
  get "/download/:booking_id" => "printer#download", as: :download
  get "signout", to: "sessions#destroy", as: "signout"
  get "/session" => "sessions#create"
  post "/api_login" => "sessions#api_login"
  resources :manager_profiles, only: [:new, :create]
  resources :attendees
  resources :events do
    resources :bookings, only: [:create]
  end
  resources :users, only: [:show]
  get "*unmatched_route", to: "application#no_route_found"
end

app/models/manager_profile.rb
class ManagerProfile < ActiveRecord::Base
  belongs_to :user
  has_many :events

  validates :company_name, presence: true
  validates :subdomain, presence: true, uniqueness: true, format: {
    with: /\A([a-zA-Z]+)/ }
  validates :company_mail, presence: true, uniqueness: true, format: {
    with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/ }
end

app/controllers/manager_profiles_controller.rb
class ManagerProfilesController < ApplicationController
  before_action :authenticate_user
  before_action :managers_current_event

  def create
    @manager_profile = ManagerProfile.new(manager_profile_params)
    @manager_profile.user_id = current_user.id
    if @manager_profile.save
      flash[:success] = "You can now create and manage events."
      path = request.base_url.gsub(%r((http:\/\/www.)|(www.)|(http:\/\/)),
                                   "http://#{@manager_profile.subdomain}.")
      redirect_to(path)
    else
      flash[:notice] = "Found Errors in form submitted!"
      render :new
    end
  end

  def new
    @manager_profile = ManagerProfile.new
  end

  def save_staffs
    staff = @event.event_staffs.new(role: staff_params[:role].to_i,
                                    user_id: staff_params[:user_id])

    success = "Successfully added Staff!"
    flash[:notice] = staff.save ? success : staff.errors.full_messages.first
    redirect_to :manage_staffs
  end

  def remove_staff
    @event.event_staffs.find_by(id: params[:event_staff_id]).destroy
    flash[:notice] = "Successfully deleted Staff!"
    redirect_to :manage_staffs
  end

  def manage_staffs
  end

  private

  def managers_current_event
    @event ||= Event.find_by_id(params[:event_id])
  end

  def manager_profile_params
    params.require(:manager_profile).permit(:company_name, :company_mail,
                                            :company_phone, :subdomain)
  end

  def staff_params
    params.permit(:role, :user_id)
  end
end

app/views/manager_profiles/_event_staffs.html.erb
<li class="collection-item avatar">
  <img src="<%= staff.user.profile_url %>" alt="User Image" class="circle">
  <span class="title"><%= staff.role.capitalize.tr("_", " ")%></span>
  <p><%= staff.user.first_name%><br>
   <%= staff.user.email%>
  </p>
  <a href="<%= remove_staff_path(event_staff_id: staff) %>"
    data-confirm="Are you sure you want to delete this staff ?">
    <i class="material-icons secondary-content">delete</i></a>
</li>

app/views/manager_profiles/edit.html.erb
<h1>ManagerProfiles#edit</h1>
<p>Find me in app/views/manager_profiles/edit.html.erb</p>

app/views/manager_profiles/manage_staffs.html.erb
<div class="our-new-custom-nav">
   <%= render partial: "layouts/nav" %>
</div>
<!-- START WRAPPER -->
<div class="container">
  <div class="wrapper">
    <div class="staff">
      <ul class="collection with-header">
        <li class="collection-header"><h5>All Staffs for <%= @event.title%> Event
        </h5></li>
        <% @event.event_staffs.each do |staff| %>
          <%= render "event_staffs", staff: staff %>
        <% end %>
      </ul>
    </div>

    <section id="content" >
      <%= form_tag do |f| %>
        <div class="col s12">
          <div class="container">
            <div class="row">
              <div class="input-field col s3">
                <%= select_tag(:role,
                             options_for_select([["Select Role"],
                                                 ["Event Staff", 1],
                                                 ["Assistant Manager", 2]]))%>
              </div>
              <div class="input-field col offset-s1 s5">
                <input type="text" class= "add_staff_field" placeholder="Enter staff email"/>
                <input type="hidden" id = "new_staff" name = "user_id" />
              </div>
              <div class="input-field col s3">
                <%= button_tag  "Submit", id: "save_staff",
                class: "btn waves-effect waves-light home_button center z-depth-0"%>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </section>
  </div>
</div>

app/views/manager_profiles/new.html.erb
 <div class="our-new-custom-nav">
    <%= render partial: "layouts/nav" %>
  </div>
      <!-- START WRAPPER -->
      <div class="wrapper">
        <section id="content" >
  <%= form_for @manager_profile do |m| %>
  <div class="col s12">
      <div class="container">
        <div class="row">
          <%= show_form_errors(@manager_profile) %>
      <div class="input-field col s10">
    <%= label_tag(:company_name, "Company Name") %>
    <%= m.text_field :company_name %>
    </div>
       <div class="input-field col s10">
    <%= label_tag(:company_mail, "Company Mail") %>
    <%= m.text_field :company_mail %>
     </div>
       <div class="input-field col s10">
     <%= label_tag(:company_phone, "Company Phone") %>
    <%= m.text_field :company_phone %>
     </div>
       <div class="input-field col s10">
    <%= label_tag(:subdomain, "Preferred Subdomain") %>
    <%= m.text_field :subdomain %>
     </div>
       <div class="input-field col s10">
    <%= button_tag  "Submit", class: "btn-large waves-effect waves-light home_button center  z-depth-0"%>
      </div>
    </div>
</div>
</div>
  <% end %>
      </section>
    </div>