config/routes.rb
Rails.application.routes.draw do
  root "welcome#index"
  get "events/new"
  post "/events/:event_id/manage_staffs" => "manager_profiles#save_staffs",
       as: :save_staffs
  get "/events/:event_id/manage_staffs" => "manager_profiles#manage_staffs",
      as: :manage_staffs
  get "/events/:event_id/remove_staff/:event_staff_id" =>
    "manager_profiles#remove_staff", as: :remove_staff
  get "/featured_events" => "welcome#featured"
  get "/popular_events" => "welcome#popular"
  get "/upcoming_events" => "welcome#index"
  get "/my_events" => "users#show"
  get "events/loading"
  get "/lookup_staffs" => "users#lookup_staff_emails"
  get "/user_info/:user_id" => "users#fetch_user_info"
  post "/paypal_hook" => "bookings#paypal_hook", as: :hook
  post "/paypal_dummy" => "bookings#paypal_dummy", as: :paypal_dummy
  get "unattend", to: "attendees#destroy", as: "unattend"
  get "auth/:provider/callback", to: "sessions#create"
  get "auth/failure", to: redirect("/")
  get "/tickets" => "bookings#index"
  get "/print/:booking_id(/:ticket_type_id)" => "printer#print", as: :print
  get "/download/:booking_id" => "printer#download", as: :download
  get "signout", to: "sessions#destroy", as: "signout"
  get "/session" => "sessions#create"
  post "/api_login" => "sessions#api_login"
  resources :manager_profiles, only: [:new, :create]
  resources :attendees
  resources :events do
    resources :bookings, only: [:create]
  end
  resources :users, only: [:show]
  get "*unmatched_route", to: "application#no_route_found"
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :category
  belongs_to :event_template
  has_many :ticket_types, dependent: :destroy
  has_many :event_staffs, dependent: :destroy
  has_many :staffs, through: :event_staffs, source: "user"
  accepts_nested_attributes_for :ticket_types,
                                allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :event_staffs,
                                allow_destroy: true,
                                reject_if: :invalid_staff_info

  has_many :bookings
  has_many :user_tickets, through: :bookings
  has_many :attendees, through: :bookings, source: "user"

  belongs_to :manager_profile
  acts_as_tenant(:manager_profile)

  # fileupload
  mount_uploader :image, PictureUploader

  validate :expiration_date_cannot_be_in_the_past
  validates :title, presence: true, length: { in: 5..250 }
  validates :description, presence: true, length: { in: 20..1000 }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :category_id, presence: true
  validates :ticket_types, presence: true

  # scope
  scope :recent_events, -> { order(created_at: :DESC).limit(12) }
  scope :featured_events, -> { order(created_at: :DESC).limit(12) }

  def expiration_date_cannot_be_in_the_past
    today = Time.zone.today
    if end_date.present? && (end_date < today || end_date < start_date)
      errors.add(:end_date, "can't be in the past")
    end
  end

  def attending?(user)
    attendees = bookings.where.not(
      payment_status: Booking.payment_statuses[:unpaid]
    ).pluck(:user_id)
    true if attendees.include?(user.id)
  end

  def self.popular_events
    find_by_sql(scope_raw_query(PopularQuery.build))
  end

  def self.search_query(search_params)
    SearchQuery.build_by(search_params)
  end

  def self.search(search_params)
    query = scope_raw_query(search_query(search_params))
    find_by_sql(query)
  end

  def self.upcoming_events
    time = Time.zone.now
    where("start_date >= ?", time).limit(12).order("start_date ASC")
  end

  def self.scope_raw_query(query)
    tenant = ActsAsTenant.current_tenant
    query = query.where(arel_table[:manager_profile_id].eq(tenant.id)) if tenant
    query.to_sql
  end

  def self.my_event_search(search_params, manager_profile_id)
    query = search_query(search_params).
            where(arel_table[:manager_profile_id].eq(manager_profile_id))
    find_by_sql(query.to_sql)
  end

  def ticket_sold
  end

  private

  def invalid_staff_info(attr)
    attr["user_id"].blank?
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user, except: [:show, :index]
  before_action :authorize_user_create, only: [:new, :create]
  before_action :authorize_user_manage, only: [:edit, :update]
  before_action :set_events, only:  [:show, :edit, :update]

  respond_to :html, :json, :js

  def new
    @event = Event.new.decorate
    @event.ticket_types.build
  end

  def index
    @categories = Category.all
    if search_params.size == 0
      @events = Event.recent_events
    else
      @events = Event.search(search_params.symbolize_keys)
    end
    respond_with @events
  end

  def show
    @booking = @event.bookings.new
    @booking.user = current_user
    @event_ticket = @event.ticket_types
    1.times { @booking.user_tickets.build }
    respond_with @event
  end

  def edit
  end

  def update
    @event.event_staffs.delete_all
    if @event.update(event_params)
      flash[:notice] = "Your Event was successfully updated"
      respond_with(@event)
    else
      flash[:notice] = "Your Event was not updated"
      respond_with(@event)
    end
  end

  def create
    @event = Event.new(event_params).decorate
    @event.manager_profile = current_user.manager_profile
    @event.title = @event.title.strip
    if @event.save
      # @event.event_staffs.create(user: current_user).event_manager!
      flash[:notice] = "Your Event was successfully created."
    else
      flash[:notice] = @event.errors.full_messages.join("<br />")
    end
    respond_with(@event)
  end

  private

  def search_params
    params.permit(:event_name, :event_location, :event_date, :category_id)
  end

  def event_params
    params.require(:event).permit(:title, :description, :start_date,
                                  :end_date, :category_id, :location, :venue,
                                  :image, :template_id, :map_url,
                                  :event_template_id,
                                  ticket_types_attributes:
                                    [:id, :_destroy, :name, :quantity, :price],
                                  event_staffs_attributes:
                                    [:user_id])
  end

  def set_events
    @event = Event.find_by_id(params[:id])
    if @event.nil?
      flash[:notice] = "Event not found"
      redirect_to events_url
    else
      @event = @event.decorate
    end
  end

  def loading
  end

  def authorize_user_create
    unless can? :manage, Event
      flash[:notice] = "You need to be an event manager"
      redirect_to(root_path)
    end
  end

  def authorize_user_manage
    unless can? :update, Event
      flash[:notice] = "You need to be a staff of this event"
      redirect_to(root_path)
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
  def user_is_attending_event(event = @event)
    event.attending?(current_user) if current_user
  end

  def attend_event_or_login(name, classes, class_1, class_2)
    button_text = name || "Attend this event"
    classes ||= "modal-trigger btn waves-effect waves-light
    btn-large our-btn-green #{class_1} #{class_2}"
    if current_user
      link_to(button_text, '#purchase_ticket_modal', class:
              classes, data: { id: "unattend", target:
                "purchase_ticket_modal" }, id: "attend")
    else
      link_to(button_text, '#login_modal', class: classes, data:
              { id: "attend", target: "login_modal" }, id: "attend")
    end
  end

  def all_template
    EventTemplate.order(:name)
  end

  def getmap(map_url)
    if map_url.nil? || map_url.strip.empty?
      new_map = ("https://goo.gl/ULMKDn") + "&output=embed"
    else
      new_map = map_url + "&output=embed"
    end
    new_map
  end

  def event_price(tickets, event)
    if user_is_attending_event(event)
      "Attending"
    elsif tickets.max == tickets.min
      tickets.max == 0 ? "Free" : number_to_currency(tickets.max, unit: "$")
    else
      "#{converter(tickets.min)} - #{converter(tickets.max)}"
    end
  end

  private

  def converter(amt)
    number_to_currency(amt, unit: "$")
  end
end

app/views/events/_attend_unattend_event_button.html.erb
<% if @event.end_date && @event.end_date > Time.zone.now %>
<div id="att2">
  <%= attend_event_or_login( "Attend this event", nil, @var1, @var2) unless user_is_attending_event %>

  <%= link_to "Unattend".html_safe,  unattend_path(:event_id => @event.id),
                   method: :get, class: "btn waves-effect waves-light btn-large our-btn-green red darken-4", data: {id: "attend"},id: "attend", remote: :true  if user_is_attending_event%>
</div>
<% end %>

app/views/events/_event.html.erb
<% @tickets = event.ticket_types.pluck(:price)%>
        <div class="col l4 s12 m4" id="fade-in">
      <div class="card small card-shadow" id="card">
        <div class="Amount">
              <%= event_price(@tickets, event) %>
        </div>
        <div class="card-image waves-effect waves-block waves-light">
          <%=link_to (image_tag event.image_url(:landing)), event  %>
        </div>
        <div class="card-content">
            <span class="card-title grey-text text-darken-4">
              <%= event.start_date.strftime("%b %d %Y") %>
            </span>
          <p><%=link_to event.title, event %></p>
        </div>

        <div class="card-action">
            <span class="card-title grey-text text-darken-4">
              <i class="fa fa-map-marker"></i>
              <%= truncate (event.venue + " " +event.location) %>
              <i class="material-icons right activator pointer tooltipped" data-delay="50" data-position="bottom" data-tooltip="view more">more_vert</i>
            </span>
        </div>
        <div class="card-reveal">
            <span class="card-title grey-text text-darken-4">Description
              <i class="material-icons right">close</i>
            </span>
          <p><%= event.description %></p>
        </div>
      </div>
    </div>

app/views/events/_eventdetails.html.erb
<% content_for :show do %>
<span class="hide-on-small-only">
<li>
  <a href="#">About</a>
</li>
<li>
  <a href="#">Schedule</a>
</li>
<li>
  <a href="#">Attendee</a>
</li>
<li>
  <a href="#">Venue</a>
</li>
</span>
<% end%>

<div class="parallax-container" data-countdown="<%= @event.start_date %>" id="index-banner">
<div style="height: 100%; width: 100%; position: absolute; background-color: rgba(0,0,0,0.4)">
  <%= render partial: "layouts/nav" %>
  <div class="section no-pad-bot">
    <div class="container">
      <div class="row center">
        <h3 class="header col s12 light our-event-title"><%= @event.title %></h3>
        <label id="counter"></label>
        <%= content_tag(:label, "#{@event.start_date} to #{@event.end_date}", style: "display: block; font-size: 24px; color: white; font-family: 'Roboto', sans-serif; margin-bottom: 5%", class: "our-event-date")  %>
        <div id="att">
          <%= render partial: "events/attend_unattend_event_button" %>
        </div>
        <%if @event.id%>
            <%= social_share_button_tag(@event.title, popup: true)%>
        <%end%>
      </div>
      <div class="row center"></div>
      <span class="hide-on-med-and-down"><br><br></span>
    </div>
  </div>
  <div class="parallax"><%= image_tag @event.image_url(:main) %></div>
</div>
</div>
<div class="description" id="description">
<div class="container center">
  <h2 class="our_description_title">Description</h2>
  <p class="our_event_description"><%= @event.description %></p>
  <div class="text-center">
    <a class="atcb-link" id="" tabindex="1">
      <i class="fa fa-calendar"></i>
      Add to My Calendar</a>
  </div>
</div>
</div>
<div class="col-md-12" class="venue" id="venue" style="height: 70%; padding:0px">
<div class="map-overlay"></div>
<iframe scrolling="no" src=<%= getmap(@event.map_url) %> width="100%" height="100%" frameborder="0" class="our-event-map-url"></iframe>
</div>

<footer class="page-footer <%= '#{@event.event_template} darken-4 ' if controller_name == 'events' && action_name == 'show'%> <%= 'landing2' if @current_page && @current_page == 'new'%>">
<div class="container">
  <div class="row">
    <div class="col l6 s12">
      <h5 class="white-text">About the Event Manager</h5>
      <p class="grey-text text-lighten-4">You can use rows and columns here to organize your footer content.</p>
    </div>
    <div class="col l4 offset-l2 s12">
      <h5 class="white-text">Links</h5>
      <ul>
        <li>
          <a class="grey-text text-lighten-3" href="#!">Link 1</a>
        </li>
        <li>
          <a class="grey-text text-lighten-3" href="#!">Link 2</a>
        </li>
        <li>
          <a class="grey-text text-lighten-3" href="#!">Link 3</a>
        </li>
        <li>
          <a class="grey-text text-lighten-3" href="#!">Link 4</a>
        </li>
      </ul>
    </div>
  </div>
</div>
<div class="footer-copyright">
  <div class="container">
    © 2014 Copyright Text
    <a class="grey-text text-lighten-4 right" href="#!">See more events by this Event manager</a>
  </div>
</div>
</footer>

app/views/events/_form.html.erb
<div class="row" id="create_background">
  <div class="event-section row remove-margin">
    <div class="col s12" style="padding: 0px 0px">
      <ul class="tabs">
        <li class="tab col s3 ">
          <a class="our-tab2-color" href="#test1">
            <i class="fa fa-plus"></i>
            Create
          </a>
        </li>
        <li class="tab col s3 ">
          <a class="our-tab2-color" href="#ticketing">
            <i class="fa fa-search "></i>
            Customize
          </a>
        </li>
        <li class="tab col s3 preview-tab disabled">
          <a class="our-tab2-color" href="#preview">
            <i class="fa fa-globe "></i>
            Preview Page
          </a>
        </li>
      </ul>
    </div>
    <%= form_for @event, html: {class: "col s12", multipart: true} do |f| %>
    <div class="col s12" id="test1">
      <div class="container margin-down">
        <div class="row">
          <%= show_form_errors(@event) %>
          <div class="row">
            <div class="input-field col s10">
              <i class="fa fa-pencil prefix icon-setting"></i>
              <label>EVENT TITLE
                <span>*</span>
              </label>
              <%= f.text_field :title, class: "validate", placeholder: "Give it a short distinct name", required: true %>
            </div>
          </div>
          <div class="row">
            <div class="input-field col l5 m5 s10">
              <i class="fa fa-map-marker prefix icon-setting"></i>
              <label>Location
                <span>*</span>
              </label>
              <%= f.text_field :location, class: "validate", placeholder: "Enter Location where it will be held", required: true %>
              <%= f.hidden_field :map_url, placeholder: "Enter Location where it will be held" %>
            </div>
            <div class="input-field col l5 m5 s10">
              <i class="fa fa-street-view prefix icon-setting"></i>
              <label>Venue
              </label>
              <%= f.text_field :venue, class: "validate", placeholder: "Enter Venue where it will be held", min: Date.today %>
            </div>
          </div>
          <div class="row">
            <div class="col s10 hide-on-med-and-down our-map">
              <div class="map-area" id="map-canvas">
                Load Maps Here
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col s12">
              <div class="row">
                <div class="input-field col s10">
                  <i class="fa fa-th-large prefix icon-setting"></i>
                  <%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a category"} , class: "browser-default", blank_option: true, required: true%>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="input-field col s5">
            <i class="fa fa-calendar prefix icon-setting"></i>
            <%= f.date_field :start_date, class: "datepicker", placeholder: "Start Date", data: {event_start_date: @event.start_date}, required: true %>
          </div>
          <div class="input-field col s5">
            <i class="fa fa-calendar prefix icon-setting"></i>
            <%= f.date_field :end_date, class: "datepicker", placeholder: "End Date", data: {event_end_date: @event.end_date} %>
          </div>
        </div>
        <div class="row col s10">
          <div id="file-uploader" class="col l6 m6 s8 offset-l3 offset-m3 offset-s2 file-uploader">
            <div class="inner-file-upload center">
              <span class="events_pic_name">
                <i class="fa fa-camera"></i>
                <br/>
                Upload Event Photo</span>

            </div>
          </div>
        </div>
        <%= f.file_field :image,  id: "event_photo_upload" %>
        <div class="row">
          <div class="input-field col s10">
            <i class="fa fa-newspaper-o prefix icon-setting"></i>
            <%= f.text_area :description, rows: 6, placeholder: "Enter description of event", required: true %>
          </div>
        </div>
        <div class="input-field col s3 offset-s4">
          <%= link_to "Next <i class='fa fa-hand-o-right'></i>".html_safe, "#", class: "col s12 btn-large waves-effect waves-light home_button center more-info z-depth-0"  %>
        </div>
      </div>
    </div>

    <div class="col s12" id="ticketing">
      <div class="container margin-down">
        <div>
          <div style="margin-bottom: 20px; margin-left: 50px;">
          </div>
          <div class="row ">
            <div class="event_ticket_field" >
              <h5>Create Ticket</h5>
              <hr>
              <%= f.fields_for :ticket_types do |tickets| %>
              <%= render "events/ticket_type_fields", :f => tickets, :locals => {:f => tickets} %>
              <% end %>
            </div>
            <div class="links">
            <%= link_to_add_association content_tag(:span, 'Add Ticket', class: "btn btn-circle"), f, :ticket_types, :class => '' %>
          </div>
          </div>
          <!-- Add Staff -->
          <div class="row">
            <div style="margin-bottom: 20px; margin-left: 50px;">
            </div>
            <div class="event_ticket_field">
              <h5>Add Staff</h5>
              <hr>
              <div class="event_staffs"><%= @event.get_event_staffs %></div>
              <%= render "staff_fields" %>
            </div>
        </div>
          </div>
        <!--End add staff -->
        <div class="row category-selected">
          <div class="row radio-select">
            <div class="input-field col s10">
              <label>Select a template</label>
              <div class="temps">
<!--Hardcoded radio button association: due to the face that i have not-->
<!--seen the rails way of doing it but it work find for now!-->
                <% all_template.each do |i|%>
                <span class="col s6 m3 center temp_image">
                  <input id="<%= i.name %>" name="event[event_template_id]" type="radio" value="<%= i.id %>"/>
                  <label for="<%= i.name %>">
                    <%= image_tag "#{i.image}" %>
                  </label>
                </span>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col s3 offset-s4 center">
        <%= link_to "Preview <i class='fa fa-hand-o-right'></i>".html_safe, "#", class: "col s12 btn-large waves-effect waves-light home_button center preview z-depth-0"  %>
      </div>

    </div>

    <%# end %>

  </div>
</div>

<div class="col s12 offset-s3" id="preview">
<!-- <iframe id="frame" scrolling="yes" src="30" width="80%" height="500px" frameborder="0" style="margin:0 auto;">
  </iframe> -->

  <div class="" id="preview-event-div" style="width: 80%; height: 500px; margin: 0 auto 1000px auto">
    <% @current_page = "new" %>
    <%= render partial: "events/eventdetails" %>
  </div>
  <div class="col s3 offset-s4 center">
    <button class="col s12 btn-large waves-effect waves-light home_button center z-depth-0">Save
      <i class="fa fa-floppy-o"></i>
    </button>
  </div>
</div>
<% end %>

app/views/events/_staff_fields.html.erb
<div class="row col s12" id="" >
  <div class="input-field col s5">
    <i class="fa fa-user prefix icon-setting"></i>
    <input type="text" class= "add_staff_field" placeholder="Enter staff email"/>
  </div>
</div>

app/views/events/_ticket_purchase_modal.html.erb
<div class="modal" id="purchase_ticket_modal">
  <div class="modal-content row">
    Buy tickets
    <%= form_for @booking, url: event_bookings_path(@event) do |f| %>
      <%#= f.text_field :ticket_type %>
      <%= f.fields_for :user_tickets do |attendee| %>
        <%= render "user_ticket_fields", f: attendee %>
      <% end %>
      <div class="col l4 m4">
        <button class="btn waves-effect waves-light" type="submit" name="action">Submit
          <i class="material-icons right">send</i>
        </button>
      </div>
    <% end %>

  </div>
</div>

app/views/events/_ticket_type_fields.html.erb
<div class="row col s12 nested-fields " id="paid_ticket_div" >
  <div class="input-field col s5">
    <i class="fa fa-ticket prefix icon-setting"></i>
    <%= f.text_field :name, placeholder: "Ticket Title"  %>
  </div>
  <div class="input-field col s2">
    <%= f.text_field :quantity, min: 0, placeholder: "Quantity" %>
  </div>
  <div class="input-field col s2">
    <%= f.text_field :price, min: 0, placeholder: "Price"%>
  </div>
  <div class="col s2 closecocoon">
    <%= link_to_remove_association "x", f, class: "btn-floating btn waves-effect waves-light red"  %>
  </div>
</div>

app/views/events/_user_ticket_fields.html.erb
<div class="col l8 m8">
  <div class="col m4">
    Ticket Type
  </div>
  <div class="col m4">
    Ticket Price
  </div>
  <div class="col m3">
    Quantity
  </div>
</div>
<% @event_ticket.each do |ticket|%>
<p>
  <div class="col l8 m8">
    <div class="col m4">
      <%= check_box :ticket_type, ticket.id, class: "browser-default"%>
      <%= label :ticket_type, ticket.id, ticket.name %>
    </div>
    <div class="col m4">
      <%= label :tickets_price, number_to_currency(ticket.price), class: "tickets_price" %>
    </div>
    <div class="col m3">
      <%= text_field :tickets_quantity, ticket.id, class: "event_ticket_input" %>
    </div>
  </div>
</p>
<% end %>

app/views/events/edit.html.erb
<%= render "events/form" %>

app/views/events/index.html.erb
  <% content_for :nav_cat do %>
    <li class="teal darken-3">
      <div class="row our-image-cover">
        <div class="col l12 m12 s12">
          <%= link_to root_path do %>
            <h3 class="header home_app_title">EventX</h3>
          <% end %>
        </div>
      </div>
    </li>

    <div class="bold" style="padding-left: 30px;"><h5> Category </h5></div>
    <li class="bold"><%= link_to "All", events_path, class:"waves-effect waves-cyan", remote: true  %>
    </li>

    <% @categories.each do |category| %>
      <li class="bold"><%= link_to "#{category.name}", events_path(category_id: category.id), class:"waves-effect", remote: true  %></li>
    <% end %>

    <li class="li-hover">
      <div class="row">
        <div class="col s12 m12 l12">
          <div class="sample-chart-wrapper">
            <div class="ct-chart ct-golden-section" id="ct2-chart"></div>
          </div>
        </div>
      </div>
    </li>

  <% end %>

<div class="showpage-header" id="index-banner">
  <div style="background-color: #222222 !important; height: 64px;">
    <%= render partial: "layouts/nav" %>
  </div>

  <div class="event-section row remove-margin">
    <div id="left">
      <div id="sidebar">
        <%= render partial: "layouts/sidebar"%>
      </div>
    </div>

    <div id="right">
      <div class="col l9 m12 s12 our-sidenav scroller2 our-sidebar-for-eventshow">
        <div class="row our-search">
          <div class="header center search_form our-search l12 m12 s12">
            <%= render partial: "welcome/search" %>
          </div>
        </div>

        <div class="content-set" id="events">
          <%= render "events_card", events: @events %>
        </div>

      </div>
    </div>
  </div>
</div>

app/views/events/index.js.erb
$("a[data-remote]").on("ajax:success", function(e, data, status, xhr){
  $('#events').html("<%=j (render 'events_card', events: @events)%>")
   $("li.bold").removeClass("active")
   $(this.parentNode).addClass('active')
})

app/views/events/loading.html.erb
<h1 class="loadrr"></h1>
<div class="center" style="height: inherit; width: inherit; padding: 15%;">
  <div class="preloader-wrapper big active">
    <div class="spinner-layer spinner-blue-only">
      <div class="circle-clipper left">
        <div class="circle"></div>
      </div><div class="gap-patch">
      <div class="circle"></div>
    </div><div class="circle-clipper right">
      <div class="circle"></div>
    </div>
    </div>
  </div>
</div>
<script>
    $('input').change(function(){
//        window.eventData.title = $(this).val()
        alert(window.eventData);
    })
//    setTimeout(function(){
//        alert(window.eventData.title);
//    }, 4000)
</script>

app/views/events/new.html.erb
<div class="create_header_background">
  <div class="creat-overlay">
    <%= render partial: "layouts/nav" %>
    <div class="container">
      <h2 class="center">Start your Event Experience
      </h2>
      <p class="center">Create it, Preview it, Publish it!</p>
    </div>
  </div>
</div>
<%= render "events/form" %>

app/views/events/show.html.erb
<%= render partial: "eventdetails" %>
<%= render partial: "ticket_purchase_modal"%>